FROM resin/rpi-raspbian:jessie

RUN apt-get update \
    && apt-get install -y ruby \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app
ADD Gemfile /app/
ADD Gemfile.lock /app/
RUN bundle install

ADD . /app
