FROM resin/rpi-raspbian:jessie

RUN apt-get update \
    && apt-get install -y \
       libcurl4-openssl-dev \
       ruby \
       ruby-dev \
    && rm -rf /var/lib/apt/lists/*
RUN gem install bundler

RUN mkdir -p /app
WORKDIR /app
ADD Gemfile /app/
ADD Gemfile.lock /app/
RUN bundle install

ADD . /app
